### ISSUE TITLE
phpipam to be present in terraform registry.

### ISSUE THREAD

**Issue by thatsk** [lord-kyron/terraform-provider-phpipam#11]
it tedious to build and get the binary then manage in .terraform which is normally ignored in code repository when multiple guise are using it. Any plan to move to terraform registry.

**Comment by pavel-z1** [comment]
Hi @thatsk 

I am personally don't use terraform registry in my projects, therefore I did not plan to publish there updates.
Honestly, this is the first terraform registry use request.

@lord-kyron , what's your opinions?

**Comment by lord-kyron** [comment]
I am also not using terraform registry, never used it before and don't have any plans to use it for now. I also see terraform registry request for first time, but don't think that it deserves time to dig into it for now.

**Comment by thatsk** [comment]
https://www.terraform.io/docs/registry/modules/publish.html

**Comment by thatsk** [comment]
its just need to sign it with it and publish so that we can just use ```YAML terraform init``` and it will fetch the provider

**Comment by lord-kyron** [comment]
That is actually not a bad idea. I will try to sign and publish there. Also will try to maintain versions there.

**Comment by thatsk** [comment]
When we can expect the provider to be in registry ?

**Comment by lord-kyron** [comment]
After short digging, I've found out, that Terraform does not allow publishing such providers in the registry at this stage. At this point only modules can be published in the registry.
Here is what is written on their page:
> Note: Publishing is currently in a closed beta. Although we do not expect this document to change significantly before opening provider publishing to the community, this reference currently only applies to providers already appearing on the Terraform Registry providers list.

So with other words - provider cannot be published to the registry so I will close this.
