### ISSUE TITLE
host_discovery_enabled is not abled to set

### ISSUE THREAD

**Issue by thatsk** [lord-kyron/terraform-provider-phpipam#15]
``` YAML
resource "phpipam_subnet" "devsrv1subnet" {
  section_id     = phpipam_section.mobitv.section_id
  subnet_address = "10.174.68.0"
  subnet_mask    = 22
  allow_ip_requests     = true
  display_hostnames =  true
  description       = "INFRA"
  master_subnet_id = phpipam_subnet.devsubnet.id
  include_in_ping = true
  create_ptr_records = true
  host_discovery_enabled = true
  vlan_id = phpipam_vlan.srv1vlan.id
}
```
while try to apply terraform apply it is giving me following error.

Error: "host_discovery_enabled": this field cannot be set

**Comment by lord-kyron** [comment]
@thatsk - again you are not reading the documentation properly.
 "host_discovery_enabled" is argument reference, which is being exported during the terraform run.
This means, that terraform only can give you reference if this is set to true or false, but you cannot set it when with terraform. This attribute is described in section "Attribute Reference - The following attributes are exported:"
https://github.com/lord-kyron/terraform-provider-phpipam/blame/master/README.md#L604
 * `host_discovery_enabled` - `true` if this subnet is included in new host
   scans.

**Comment by thatsk** [comment]
so when we are creating subnet can't we set this option ?

**Comment by lord-kyron** [comment]
Yes
