### ISSUE TITLE
Run this provider on Windows 10 x64

### ISSUE THREAD

**Issue by basic39** [lord-kyron/terraform-provider-phpipam#18]
Hello,
when I try to run this provider on Windows 10 x64, I get following error: 
"The program or feature ... cannot start or run due to incompatibity with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available." It looks like it is a 16 Bit app.
As I know, there is no way to run x16 on x64 windows.

Can you please provide an other version of the provider?

**Comment by lord-kyron** [comment]
I've never used it on windows so I am not sure abot it.
@pavel-z1 - what do you think about that?

**Comment by pavel-z1** [comment]
I am personally don't use Windows too.

But, customers can build exe file themselves.
Here described how to build GO application for Windows x64:
https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04
https://stackoverflow.com/questions/41566495/golang-how-to-cross-compile-on-linux-for-windows

Example:
```
GOOS=windows GOARCH=amd64 go build
```

Installation of terraform on Windows:
https://learn.hashicorp.com/terraform/getting-started/install.html

WIndows plugin directory - `%APPDATA%\terraform.d\plugins`
https://www.terraform.io/docs/extend/how-terraform-works.html

I've tested phpipam terraform plugin on windows. Seems all works:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/53462452/86139833-dbc50780-baf8-11ea-87a5-20d620b84ccc.png">
