### ISSUE TITLE
phpipam_subnet can't set "host_discovery_enabled"

### ISSUE THREAD

**Issue by rhysxevans** [lord-kyron/terraform-provider-phpipam#22]
Hi

We are trying to turn on host discovery  

```
resource "phpipam_subnet" "subnet" {
  for_each       = var.ipam_subnets
  section_id     = data.phpipam_section.section[each.key].section_id
  description    = each.value[2]
  subnet_address = each.value[0]
  subnet_mask    = each.value[1]
  include_in_ping = true
  host_discovery_enabled = true
  display_hostnames = true
  allow_ip_requests = true
  scan_agent_id = 1
}
```

We get `Error: "host_discovery_enabled": this field cannot be set`  removing the `host_discovery_enabled` and it works as expected

Any ideas?

PHPIPAM: 1.4.1
TF: terraform-provider-phpipam-1.1

**Comment by rhysxevans** [comment]
However if manually setting the value to "true" in PHPIPAM manually, terraform will report reverting the setting (to the default of not enabled), however the setting does not actually get changed

**Comment by lord-kyron** [comment]
@rhysxevans some changes and new commits and fixes are going to come soon. We will try to fix those reported issues!
Thanks for you patience!

**Comment by pavel-z1** [comment]
Bug fixed https://github.com/lord-kyron/terraform-provider-phpipam/commit/d7ce11f99e46bb31abbf58affa58a59a2f306815
