### ISSUE TITLE
Provider doesn't load

### ISSUE THREAD

**Issue by raffus** [lord-kyron/terraform-provider-phpipam#24]
Hi there,

Following installation instructions, terraform seems to be ignoring local plugins folder.

After running:
```
git clone ...
go install
go build
cp terraform-provider-phpipam ~/.terraform.d/plugins/
```

I then ran "terraform init", but had the following error:

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/vsphere v1.24.0
- Finding latest version of hashicorp/phpipam...

Error: Failed to install provider

Error while installing hashicorp/phpipam: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/phpipam

```

```
$ ls -la ~/.terraform.d/plugins/
total 53248
drwxr-xr-x  3 rafael  staff        96 10 Set 13:39 .
drwxr-xr-x  5 rafael  staff       160 10 Set 13:21 ..
-rwxr-xr-x  1 rafael  staff  27127900 10 Set 13:37 terraform-provider-phpipam
```

I've even added phpip into local .terraform folder:

```
$ ls -la .terraform/plugins/registry.terraform.io/hashicorp/phpipam
total 52992
drwxr-xr-x  3 rafael  staff        96 10 Set 13:33 .
drwxr-xr-x@ 4 rafael  staff       128 10 Set 13:33 ..
-rwxr-xr-x  1 rafael  staff  27127900 10 Set 13:33 phpipam
```

Still having same error..

Any ideas?

Huge thanks.
BR,
Rafael

**Comment by lord-kyron** [comment]
Hi @raffus,
If you are using terraforn 0.13 take a look at the comments in this issue:
https://github.com/lord-kyron/terraform-provider-phpipam/issues/21

**Comment by raffus** [comment]
Hey @lord-kyron, thank you for your reply.
I've got it working out, but had to do a work around and burn a lot of my brain on it.

My ubuntu had a broken GoLang install.
I then downloaded the MAC version, compiled the provider following instructions above.
Then I had to add the plugin files into the local phpipam terraform folder.
The bug was on the directory structure. When fixed, it worked.

So this is the path I've created in order to work:
project-name/.terraform/plugins/registry.terraform.io/hashicorp/phpipam/1.0/darwin_amd64/

and then saved the plugin there:
project-name/.terraform/plugins/registry.terraform.io/hashicorp/phpipam/1.0/darwin_amd64/terraform-provider-phpipam

By following the vsphere structure I was able to reproduce it and then finally got it working.

I guess its just a matter of updating the install doc and it should work.

Huge thanks and please consider updating the documentation. Now I'm flying here using terraform and phpipam.

BR,
Rafael

**Comment by pavel-z1** [comment]
Hi @lord-kyron ,
We have previously attempt to add our plugin to the Terraform Registry. Previously we had issue because ot was limits from terraform v12.

But now, seems, Terraform support this.
Can you please try again to publish phpipam terraform provider to the Terraform Registry?

**Comment by lord-kyron** [comment]
Yes, I will try again.
Will you be able to check and fix the host_discovery and is_folder problems from issues list?

**Comment by pavel-z1** [comment]
Hi @lord-kyron , bug with host_discovery fixed.
You had time to publish phpipam terraform provider to the Terraform Registry?

**Comment by lord-kyron** [comment]
Let's implement the latest changes and pull requests and I will compile the new binary. Then will try to register in the registry.
However in the meantime - @pavel-z1 - I found this repo - https://github.com/Ouest-France/terraform-provider-phpipam
Can you check if this is clone of our repo and if can use something of its features/implementations?

**Comment by pavel-z1** [comment]
Hi @lord-kyron, at a quick glance this repo https://github.com/Ouest-France/terraform-provider-phpipam has commits with features that we have already.
I don't have currently free time to perform deep searching/investigation/improvements of the new features, therefore any community help would be helpful.

Currently all pull requests closed, latest changes in the master branch.
You can create new release and push provider to the terraform registry )
