### ISSUE TITLE
Invite to Publish to the Terraform Registry

### ISSUE THREAD

**Issue by aicarmic** [lord-kyron/terraform-provider-phpipam#26]
👋  Hi there! We noticed this provider is on our list of community providers, however it has not yet been published to the newly-released Terraform Registry for Providers (registry.terraform.io). We'd like to invite you to get it published, since it makes using and installing it much easier for anyone using Terraform 0.13! Instructions for doing so are available [here](https://www.terraform.io/docs/registry/providers/publishing.html). Please note that we will soon be redirecting the [community listing page](https://www.terraform.io/docs/providers/type/community-index.html) to registry.terraform.io.

Thanks for your contributions and we look forward to seeing this provider listed soon!

Thanks,
Team Terraform @ HashiCorp

**Comment by lord-kyron** [comment]
@VasseurLaurent - I can see you forked our repo and published it without changes to Terraform Registry. Can you please remove it from there now, as we have the main repo registered?

**Comment by VasseurLaurent** [comment]
Hello @lord-kyron , great news, I am not sure that Terraform registry has a feature for that. I have deleted the github repository , I hope it will make its reference in Terraform registry disappear as well

**Comment by lord-kyron** [comment]
@VasseurLaurent Thank you! 💗

**Comment by lord-kyron** [comment]
@aicarmic - can you help us remove @VasseurLaurent duplicate of our provider from Terraform registry as it is not needed there anymore?

**Comment by justincampbell** [comment]
Done! The other provider should now redirect to this one: https://registry.terraform.io/providers/VasseurLaurent/phpipam/latest

**Comment by lord-kyron** [comment]
@justincampbell - thank you!
