### ISSUE TITLE
nostrict "yes"

### ISSUE THREAD

**Issue by pmraz123** [lord-kyron/terraform-provider-phpipam#34]
Hi

Is it possible to implement nostrict option when we adding IP via terraform to phpipam? 
It would allow to use broacast and subnet IP. 

If I have huge mgmt range /18 for example and building "sub-management" ranges within /18 like /29 i would like to use entire /29 as it is not real subnet. But it is associated to specific resources.

**Comment by pavel-z1** [comment]
Hi @pmraz123 

I don't see parameter no strict for address controlled in the phpipam documentation https://phpipam.net/#addresses

You have example how to use no strict with phpipam API call?

**Comment by pmraz123** [comment]
Hi, we "solved" it ...we simply dont use network and broadcast. I have /19 mgmt range and building block of /29 mgmt sub-ranges and wanted to use entire /29 as it is not real "network" . But PHPIPAM didnt allow me set broadcast and network which were legitime IPs. We have now other issue - > request more free IPs in single run from one range. Looks we always get just very 1st one when we want to use it. PHPIPAM itself I think marked/filled all 4 for example but when I want to use that IP in terraform, just very 1st one is returned :(
