### ISSUE TITLE
"location_id": this field cannot be set

### ISSUE THREAD

**Issue by MrKoopaKiller** [lord-kyron/terraform-provider-phpipam#40]
**Affected Resource(s)**
`phpipam_subnet resource`

**Terraform Version:** `0.15.3` / `1.0.8`

**Provider Version:** `1.2.8`

**Issue:** Create a subnet with `location_id` field returns an error.

**Terraform code**
```
terraform {
  required_providers {
    phpipam = {
      source  = "lord-kyron/phpipam"
      version = "1.2.8"
    }
  }
}

provider "phpipam" {
  app_id       = "api_client"
  endpoint   = "http://localhost/api"
  password  = "******"
  username  = "admin"
  insecure    = true
}

resource "phpipam_subnet" "subnet" {
  section_id           = 10
  subnet_address = "10.0.0.0"
  subnet_mask      = "24"
  location_id          = 60
}

```

**Output:**
```
╷
│ Error: "location_id": this field cannot be set
│ 
│   with phpipam_subnet.subnet,
│   on main.tf line 18, in resource "phpipam_subnet" "subnet":
│   18: resource "phpipam_subnet" "subnet" {
│ 
```

**Expected Behavior**
Subnet created using the correct `location_id`.

**Comment by MrKoopaKiller** [comment]
@lord-kyron no sure, but should the `location_id` be here as well ?

https://github.com/lord-kyron/terraform-provider-phpipam/blob/master/plugin/providers/phpipam/subnet_structure.go#L18

**Comment by zxin821127** [comment]
how To solve   location_id Can not choose?  thx；
