### ISSUE TITLE
documentation around resource imports

### ISSUE THREAD

**Issue by zbialik** [lord-kyron/terraform-provider-phpipam#49]
Hi there!

I noticed in the current docs, there's nothing mentioned around how to `terraform import` specific resources. 

I would ideally like to do a `terraform import` for a `phpipam_first_free_subnet` resource so that we can migrate some of our IP subnets created in phpIPAM UI to our IaC repository.

Is this possible?

Thanks!

**Comment by cristicalin** [comment]
The current implementation with terraform plugin sdk v1 does not have the necessary mechanism do support importing resources. https://github.com/lord-kyron/terraform-provider-phpipam/pull/51 updates the provider to use sdk v2 and adds the necessary support to allow importing resources safely.
