### ISSUE TITLE
Data source phpipam_subnet returns gateway_id as empty string when number is expected

### ISSUE THREAD

**Issue by gcamblin** [lord-kyron/terraform-provider-phpipam#50]
**Affected Resource(s)**
phpipam_address data source

**Provider Version**
v1.3.6

**Terraform Version**
v1.1.9

**Terraform Script**

```
data "phpipam_subnet" "subnet" {
  subnet_address = "${var.subnet}"
  subnet_mask    = "${var.cidr}"
}

data "phpipam_first_free_address" "next_address" {
  subnet_id = data.phpipam_subnet.subnet.subnet_id
}

resource "phpipam_address" "ip" {
  subnet_id   = data.phpipam_subnet.subnet.subnet_id
  ip_address  = data.phpipam_first_free_address.next_address.ip_address
  hostname    = "${var.vmname}"
  description = "Managed by Terraform"

  lifecycle {
    ignore_changes = [
      subnet_id,
      ip_address,
    ]
  }
}

#// Determine Gateway IP by gateway_id
data "phpipam_address" "gateway" {
  address_id    = data.phpipam_subnet.subnet.gateway_id
}
```

**Output**

> Error: Incorrect attribute value type
> 
> on ../../../../terraform-modules/vsphere/test-node-phpipam/main.tf line 26, in data "phpipam_address" "gateway":
> 26:   address_id    = data.phpipam_subnet.subnet.gateway_id
> 
> data.phpipam_subnet.subnet.gateway_id is ""
> 
> Inappropriate value for attribute "address_id": a number is required.

**Expected Behavior:**

I was expecting Terraform to look up and return the gateway IP address but it fails with data.phpipam_subnet.subnet.gateway_id returned as an empty string when an integer is needed.

**Comment by lord-kyron** [comment]
@pavel-z1 Some ideas here?

**Comment by pavel-z1** [comment]
Hi @gcamblin 
This is the same issue https://github.com/lord-kyron/terraform-provider-phpipam/issues/42
Related to the bug in the phpipam API.
Try to write to the phpipam project to fix API response
