### ISSUE TITLE
release a new build with updated sdk to pick up support for http_proxy

### ISSUE THREAD

**Issue by cristicalin** [lord-kyron/terraform-provider-phpipam#62]
Hello @lord-kyron.

A fix to the phpipam SDK was accepted https://github.com/pavel-z1/phpipam-sdk-go/pull/11 that enables the sdk to use the http proxy set through `http_proxy` environment variable. Could you issue a new build with the updated version of the SDK?

**Comment by lord-kyron** [comment]
WIll be be release soon next week after implemeting some more changes and improvements

**Comment by lord-kyron** [comment]
@cristicalin 
New version 1.4.0 was released, including the changes you asked about!
Enjoy!
