### ISSUE TITLE
phpipam_vlan fails if matching vlan number exist in different domain

### ISSUE THREAD

**Issue by mahsoud** [lord-kyron/terraform-provider-phpipam#66]
Noticed that provider creates an entry in IPAM for new VLAN, but fails to validate the change with error:

Error: VLAN search returned either zero or multiple results. Please correct your search and try again

this happens in situations where vlan number is already in ipam under different domain

**Comment by lord-kyron** [comment]
@pavel-z1 some ideas here?

**Comment by pavel-z1** [comment]
I will check this.
Possible we will need to create new l2domain controller in the sdk and provider.

**Comment by lord-kyron** [comment]
Fixed with https://github.com/lord-kyron/terraform-provider-phpipam/pull/68
New version will be released tomorrow.
