### ISSUE TITLE
Feature Request: Please implement new phpipam_location resource and data source

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lord-kyron/terraform-provider-phpipam#75]
It would be useful to be able to define, or look up a location from the PHPIPAM service.

**Comment by lord-kyron** [comment]
@pavel-z1

**Comment by pavel-z1** [comment]
Hi @JonTheNiceGuy 
We do not have a phpipam tools controller in either the[ PHPIMAM SDK](https://github.com/pavel-z1/phpipam-sdk-go) or the [PHPIPAM Terraform Provider](https://github.com/lord-kyron/terraform-provider-phpipam) 
I have no plans to develop this controller for SDK and Terraform Provider.

You feel free to develop this controller and create Pull requests to SDK project and here.

**Comment by lord-kyron** [comment]
Closing for long inactivity.
