### ISSUE TITLE
Feature Request: Please implement new phpipam_device and phpipam_device_type resource and data source

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lord-kyron/terraform-provider-phpipam#77]
It would be useful to be able to create or look up network devices and their related device types from the PHPIPAM service.

## Devices

API endpoint is: `/api/<API_NAME>/devices/`. e.g.

```
curl https://phpipam.example.org/api/terraform/devices/ -H "token: DECAFBAD1234567890abcdefghijklmnopq"
{"code":200,"success":true,"data":[{"id":"1","hostname":"Router","ip":"192.0.2.1","type":"2","description":null,"sections":"1","snmp_community":"decafbad","snmp_version":"3","snmp_port":"161","snmp_timeout":"1000","snmp_queries":"get_system_info;get_arp_table;get_mac_table;get_interfaces_ip;get_routing_table;get_vlan_table;get_vrf_table","snmp_v3_sec_level":"authPriv","snmp_v3_auth_protocol":"SHA","snmp_v3_auth_pass":"deadbeef","snmp_v3_priv_protocol":"AES","snmp_v3_priv_pass":"abcd1234","snmp_v3_ctx_name":null,"snmp_v3_ctx_engine_id":null,"rack":"0","rack_start":"0","rack_size":"0","location":"0","editDate":"2023-06-08 08:53:13"}],"time":0.018}
```

When creating a new resource your mandatory fields would be hostname, ip, type (see below), and sections (which we'd get from `phpipam_section` data or resource). Optional fields would be rack, rack_start, rack_size, location, snmp_community, snmp_version, snmp_port, snmp_timeout, snmp_queries, get_system_info (I'm not sure where to get these values from, but the example above has the list from the version 1.5.3), snmp_v3_sec_level (only relevant if snmp_version is 3), snmp_v3_auth_protocol, snmp_v3_auth_pass, snmp_v3_priv_protocol, snmp_v3_priv_pass, snmp_v3_ctx_name and snmp_v3_ctx_engine_id

## Device Types

API endpoint is: `/api/<API_NAME>/tools/device_types/`. e.g.

```
curl https://phpipam.example.org/api/terraform/tools/device_types/ -H "token: DECAFBAD1234567890abcdefghijklmnopq"
{"code":200,"success":true,"data":{"code":200,"success":true,"data":[{"tid":"1","tname":"Switch","tdescription":"Switch"},{"tid":"2","tname":"Router","tdescription":"Router"},{"tid":"3","tname":"Firewall","tdescription":"Firewall"},{"tid":"4","tname":"Hub","tdescription":"Hub"},{"tid":"5","tname":"Wireless","tdescription":"Wireless"},{"tid":"6","tname":"Database","tdescription":"Database"},{"tid":"7","tname":"Workstation","tdescription":"Workstation"},{"tid":"8","tname":"Laptop","tdescription":"Laptop"},{"tid":"9","tname":"Other","tdescription":"Other"}],"time":0.005}
```

This would be useful as a data source, and I'm ambivalent about creating it as a resource.

If you do create this as a resource, your required field is just tname (probably worth renaming to name) and it has an optional field of tdescription (probably worth renaming to description).

**Comment by lord-kyron** [comment]
Closing for long inactivity.
