### ISSUE TITLE
Importing vlan fails

### ISSUE THREAD

**Issue by peterbaumert** [lord-kyron/terraform-provider-phpipam#87]
Hi,

I am somehow not able to import vlans.

```
resource "phpipam_vlan" "test" {
  number       = 1
  name         = "test"
  l2_domain_id = 1
}
```

when I do `terraform import phpipam_vlan.test 19`

it gives me the error

```
╷
│ Error: vlan_id or number not defined, cannot proceed with reading data
│ 
│ 
╵
```

phpipam version: v1.7.0 dbversion 41
Terraform v1.7.4
provider registry.terraform.io/lord-kyron/phpipam v1.5.2

**Comment by peterbaumert** [comment]
created #88 for this. please review.

**Comment by pavel-z1** [comment]
PR merged https://github.com/lord-kyron/terraform-provider-phpipam/pull/88
