### ISSUE TITLE
Insecure option

### ISSUE THREAD

**Issue by D4NNYX** [lord-kyron/terraform-provider-phpipam#9]
Hello,

I really miss the insecure option to avoid verifying SSL certificates as other providers can, would it be possible to implement it?

**Comment by pavel-z1** [comment]
Hi @D4NNYX 

I think that insecure SSL option could be added.
I will try to check next week.

**Comment by lord-kyron** [comment]
@pavel-z1 - did you get a chance to review this possibility?

**Comment by pavel-z1** [comment]
Hi @lord-kyron , I have not had time to check yet.
I hope that this week there will be such an opportunity.

**Comment by thatsk** [comment]
@D4NNYX  can you provide me instruction to configure phpipam with SSL on centos7 or any distro. official doc does not supply with ssl.so can't be able to configure this provider.

**Comment by pavel-z1** [comment]
Added insecure feature to the phpipam provider.

Commits:
1. https://github.com/lord-kyron/terraform-provider-phpipam/commit/d5e0fa4bfb1526f2f252fb93786d9895a70ff20b
2. https://github.com/pavel-z1/phpipam-sdk-go/commit/f6826881bb37b6ae2970cdab252169018daaae4b

Usage example:
```
provider "phpipam" {
  app_id   = "test"
  endpoint = "https://phpipam.example.com/api"
  password = "PHPIPAM_PASSWORD"
  username = "Admin"
  insecure = true
}
```
